#!/bin/sh -e
# NAME=slave-clear
# DESCRIPTION=TODO
# DESTROYS_HDD=false
# IS_INTERACTIVE=false
# POWEROFF_DURING_TEST=false
# VERSION=0.1
# TAGS=
# DEPENDS=
# VAR=GROUP_ID:int:0:TODO

. _inq-config-global; . $SHARE_DIR/functions-test

pool_clear $GROUP_ID

test_succeeded
