#!/usr/bin/env ruby

$LOAD_PATH.unshift('.')
require 'raid/baseraid'

models = {}

RAID::BaseRaid::query_adapters.each { |ad|
	a = RAID::RAIDS[ad[:driver]].new(ad[:num])
	a.logical_clear
	exit 0 if a._physical_list.empty?
	a._physical_list.values.each { |ph|
		(models[ph[:model]] = models[ph[:model]] || {}).merge!(ph[:revision] => ph[:revision])
	}
}

exit 1 if models.values.find { |v| v.size > 1 }
