File/CopyHandler:
  paths: ["**/*.css", "**/*.js", "**/*.jpg", "**/*.png", "**/*.gif", "**/*.zip", "**/*.ico", "google*.html", "y_key_*.html", "robots.txt"]

---
sf-project.html:
  title: SF.net project
  inMenu: true
  url: http://www.sourceforge.net/projects/inq/
