File/CopyHandler:
  paths: ["**/*.css", "**/*.js", "**/*.jpg", "**/*.png", "**/*.gif", "**/*.zip", "**/*.ico"]

---
sf-project.html:
  title: SF.net project
  inMenu: true
  url: http://www.sourceforge.net/projects/inq/
